# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  #secret_key_base: fc110c8e9b4a7ddc7fa38c077b819d7fd1279ebb1269e8a205626107e91819b2c10b7fca2e3b82de190d3a64930a53c35df7f7ba1250bd3bc4bd98dc15dc7370
  secret_key_base: MDAwYTFhZmY2ZTMxOWM5Y2NlY2I3YWZj

test:
  secret_key_base: a5c0decc597acfe07f1f569164f188f5d5c89292d47230771933a2fe1c5a08b4118166b91311a5a942f6e23149518b26c327672ea82803d26d6c1461104ecb70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
